### ISSUE TITLE
Live output not working with the JOBs

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck-plugins/py-winrm-plugin#12]
After the "Live output" implementation looks like the "Job's" output is interrupted whenever there are long running commands on the remote server where it does not output anything. But once the command execution is completed the rest of the results/output is not returned back to the console anymore. The initial output (the immediate) output does return to the console successfully. But if the command is taking 20+Sec seems like the output is broken after that.

**Comment by hs-hub-world** [comment]
Here is more info. the error occurs with any delays basically. When using Sleep 1 you'll see the error when Sleep 0 there is no error.
No Errors when executing this command:write "sleeping..1 sec";sleep 0;get-date
You see errors when executing this command: write "sleeping..1 sec";sleep 1;get-date

![python-winrm_liveoutput-error-1](https://user-images.githubusercontent.com/20629911/48782159-65acbd80-ec92-11e8-8444-d7386d86cf55.png)
![python-winrm_liveoutput-2](https://user-images.githubusercontent.com/20629911/48782171-680f1780-ec92-11e8-8310-1ba1b7d01081.png)

**Comment by ltamaster** [comment]
Hi @hs-hub-world , 

Can you share your job to test it?

Thanks
Luis

**Comment by ltamaster** [comment]
Hi @hs-hub-world ,

I added a new release, please let me know if you can test it.

![screenshot from 2018-12-04 15-29-58](https://user-images.githubusercontent.com/6034968/49464582-0b574500-f7da-11e8-93bf-4d9dcf7f17c9.png)


Thanks
Luis

**Comment by hs-hub-world** [comment]
Thank you @ltamaster !  It works perfectly now.
There is a small typo in line 125 (link below). Folling should be Following
https://github.com/rundeck-plugins/py-winrm-plugin/commit/8d7a2be060d4238dc8c4a846b47a4d7badd6bfa6

You have made Rundeck look and feel like an enterprise/professional product.  Thanks again!
