### ISSUE TITLE
plugin fails to copy script file

### ISSUE THREAD

**Issue by ondrejbaranek** [rundeck-plugins/py-winrm-plugin#15]
Plugin should copy script file to location C:\WINDOWS\TEMP\7591-6854-hostname001-masterless-windows.ps1
When I check that location, file copier created folder C:\WINDOWS\TEMP\7591-6854-hostname001-
and script masterless-windows.ps1 in that folder.
It is Windows 2016 and using NTLM auth.

**Comment by ltamaster** [comment]
Hi @ondrejbaranek ,

Can you share your node definition and your job?

For me, it looks OK

<img width="1094" alt="screenshot 2018-12-27 11 39 22" src="https://user-images.githubusercontent.com/6034968/50483832-3fceb300-09cc-11e9-8a00-47f3eedace8d.png">

**Comment by tylersoren** [comment]
I was having the same exact issue and was able to resolve with a couple modifications to the winrm-filecopier script.  Details are in pull request #18

**Comment by mrmantas** [comment]
We were having the same issue, it seems to appear only when using script file from URL. Inline script is ok. Pull request #18 fixes it.
