### ISSUE TITLE
Plugin on Windows 

### ISSUE THREAD

**Issue by damienvanrobaeys** [rundeck-plugins/py-winrm-plugin#19]
I have installed rundeck on a Windows 10 computer.
Is this plugin compatible with Windows ? 
I can use it easily on centos but from windows i get the below message:

[Winrmpython]can not run program python: createprocess error=2, the system can not find the file specified.

On the centos server i also installed python. I tried to install the latest python on my windows10 but still same message.

**Comment by thomas-illiet** [comment]
Hey @ltamaster, do you have any information for this issue ?

**Comment by hs-hub-world** [comment]
I did try running rundeck on Windows then eventually I gave up and just went back to CentOs. with windows you need to make sure all the Env. variables are in place i.e. Java and Python. you need to make sure the correct python and packages/plugins are installed. and I believe default rundeck configuration file(s) may need to be updated to point to the correct path (relative to windows diretory,etc..)
oh and don't forget the NTFS folder security permissions, etc.

good luck
H

**Comment by ltamaster** [comment]
Hi @damienvanrobaeys and @thomas-illiet 

I tried it on windows and I got some issues. I don't recall it now.
I am trying to upgrade the plugin to be compatible with python3 and then I will check the windows compatibility  install again

Luis

**Comment by ltamaster** [comment]
Hi @damienvanrobaeys  and @thomas-illiet 
I published a new version that worked for me on a windows box.
Anyway, as the previous response, you need to install python on the windows box plus the dependencies (pywinrm for example)

Please, any feedback can be useful.

Thanks
Luis
