### ISSUE TITLE
NonZeroResultCode: [WinRMPython] Result code: 1

### ISSUE THREAD

**Issue by FireHelmet** [rundeck-plugins/py-winrm-plugin#21]
Hello,

I encounter an issue when I execute some powershell commands, the error is:

Failed: NonZeroResultCode: [WinRMPython] Result code: 1

![image](https://user-images.githubusercontent.com/17533298/54521027-5866bd80-496a-11e9-8eef-e741a8c6fce1.png)

This error is already mentionned in the readme but my execution policy setting is good:

![image](https://user-images.githubusercontent.com/17533298/54520972-3836fe80-496a-11e9-874c-cd2ea81cbea7.png)

Could you help me ?

Thank you so much for this plugin !

**Comment by hs-hub-world** [comment]
Try to output the $LastExitCode  

Also if your command outputs any "warning" (which will not be shown from rundeck/python script) that will also throw NonZeroResultCode. Hence try to set the WarningPreference=SilentlyContinue like so: $WarningPreference = 'SilentlyContinue' that should be the first line before execution.

also if your command supports "-erroraction silentlycontinue" you can use that too, but that has other side-affects too.  You'll now know if your command failed, etc..

Keep in mind: Any exit code that is non-zero whether it's from a warning or error rundeck/python script will fail the script/job.

**Comment by FireHelmet** [comment]
Hello @hs-hub-world 

Thank you for your quick answer.
To be more clear, I want to move to this plugin because the plugin https://github.com/NetDocuments/rd-winrm-plugin is not supported now.

My script is working on the rd-winrm-plugin mentionned above but not on WinRMPython.
I just tried to add "powershell" explicitly and the command works:

![image](https://user-images.githubusercontent.com/17533298/54549710-e82c5c00-49aa-11e9-8840-2136c4ec13e1.png)

You can see the first two lines are executed on the shell instead of powershell at my point of view.

Maybe it's an issue on node executor ? but this one is set on powershell, so ??

![image](https://user-images.githubusercontent.com/17533298/54549848-3b9eaa00-49ab-11e9-8c7d-423b5d515a55.png)

Thank you for your help.

**Comment by ltamaster** [comment]
Hi @FireHelmet 

You can avoid that error setting the invocation script and the extension on the workflow-step, like this:

<img width="949" alt="Screenshot 2019-04-08 12 00 31" src="https://user-images.githubusercontent.com/6034968/55738881-fbed4000-59f5-11e9-9514-405034cf101c.png">

**Comment by FireHelmet** [comment]
Hi @ltamaster ,

Thank you for your answer, it works !

So these additional settings are mandatory ? because it's not explained in the readme of the github repo. Because the powershell env is already in windows path variable:
 
![image](https://user-images.githubusercontent.com/17533298/55865348-75179f00-5b7e-11e9-9979-5617de05a769.png)

Thank you !

**Comment by FireHelmet** [comment]
Hi @ltamaster 

Just an update
Could you answer to my previous comment ? :)

Thank you !

**Comment by ltamaster** [comment]
Hi @FireHelmet,

Sorry for the delay.

You need to set the `powershell` invocation script on the job because Rundeck by default try to generate a temporary file with the `.bat` extension (when you try to run a script to a windows box). So the invocation script overwrites that default behavior.

Luis
