### ISSUE TITLE
Issue : A XML is shown in job result

### ISSUE THREAD

**Issue by FireHelmet** [rundeck-plugins/py-winrm-plugin#22]
Hello !

After to have updated the plugin to the latest version 2.0.0, when I run a previously working job from 1.0.10 version, the job result show this now :

![image](https://user-images.githubusercontent.com/17533298/55865925-9b8a0a00-5b7f-11e9-99d5-ff04873e18b4.png)

Thank you for your support !

**Comment by ltamaster** [comment]
Hi @FireHelmet,

What are you running on the job, in order to reproduce it?
Which python version are you using?

Thanks
Luis

**Comment by FireHelmet** [comment]
Hi @ltamaster ,

I run that :

`$objUser = New-Object System.Security.Principal.NTAccount("@option.Domain@", "@option.UserAccount@") 
$strSID = $objUser.Translate([System.Security.Principal.SecurityIdentifier]) 
write-host "The SID of @option.UserAccount@ is $strSID"`

I'm using python 2.7.5

I also uploaded the job definition:

[Get-Sid.zip](https://github.com/rundeck-plugins/py-winrm-plugin/files/3073841/Get-Sid.zip)

Thank you for your support

**Comment by ltamaster** [comment]
which windows version are you connecting with?
it worked OK for me

<img width="1050" alt="Screenshot 2019-04-12 14 05 45" src="https://user-images.githubusercontent.com/6034968/56057142-1db73180-5d2c-11e9-8fc9-6d82ec857164.png">

**Comment by FireHelmet** [comment]
Hi @ltamaster ,

I have ran the job on Windows 2008 R Standard with Powershell 5.1. I also have tested on Win 2012 R2 and Win 2016.

It's the same thing.

But my Python version is not the same ! I'm on 2.7.5, already uptodate from yum package manager.

![image](https://user-images.githubusercontent.com/17533298/56116899-3c553c80-5f67-11e9-9812-36ede1d86060.png)

**Comment by ltamaster** [comment]
Hi @FireHelmet 
Can you try with the last 2.0.2?

Thanks

**Comment by FireHelmet** [comment]
Hello @ltamaster 

Yes, just now and it's working well 👍 

Tested on Win2008R2, Win2012R2 and Win2016
Based on Rundeck 3.0.21 with py-winrm 2.0.2 and python 2.7.5

Thank you for your support !
