### ISSUE TITLE
Cannot run program "python" w/ Ubuntu

### ISSUE THREAD

**Issue by Chris-SG** [rundeck-plugins/py-winrm-plugin#25]
While I am not so sure this is directly related to this plugin, the error is being caused by attempting script execution or command execution via this plugin. Output is the following:

```

Failed dispatching to node Server: [WinRMcpPython] Cannot run program "python": error=2, No such file or directory
--
Execution failed: 24 in project Servers: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [Server: IOFailure: [WinRMcpPython] Cannot run program "python": error=2, No such file or directory]}, Node failures: {Server=[IOFailure: [WinRMcpPython] Cannot run program "python": error=2, No such file or directory]}, status: failed]

```

Python is definitely installed, with python3 aliased to python. I also installed python on the destination, however it shouldn't be needed (this was not an issue when I was using Rundeck from a windows host).

Have I possibly missed any kind of configuration?

**Comment by ltamaster** [comment]
Hi @Chris-SG 
Maybe rundeck instance has not found the python installation path. 
You can double check it running the command `python --version` to the rundeck node.

<img width="700" alt="Screenshot 2019-04-16 09 49 19" src="https://user-images.githubusercontent.com/6034968/56215000-ecd94400-602c-11e9-8308-a2ac01bb99a0.png">

**Comment by ltamaster** [comment]
Hi @Chris-SG

Was you able to fix this?

Luis

**Comment by Chris-SG** [comment]
Hi @laubstein ,

I did, however I cannot remember exactly what I had to do since it was so long ago, sorry!

**Comment by tuxisma** [comment]
Plugin is looking for python executable. 
Creating a simlink works for me:
sudo ln -s /usr/bin/python2 /usr/bin/python
