### ISSUE TITLE
winrm-exec.py Errors

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck-plugins/py-winrm-plugin#27]
Hi, with the latest release of py-winrm-plugin I am seeing these errors when executing PS scripts. 
Note, I rolled back to previous version 2.0.0 and that works fine. 

Hope the image provides enough data.

![image](https://user-images.githubusercontent.com/20629911/57028138-28f6d200-6bf3-11e9-9d12-e6af849f656b.png)

Thanks,
HS

**Comment by ltamaster** [comment]
Hi @hs-hub-world:

Can you share some info about your environment?
* python version
* windows remote version
* an example of your script if it is possible.

Thanks
Luis

**Comment by hs-hub-world** [comment]
Hello @ltamaster 

Python version = 2.7.5
PIP PyWinrM = pywinrm (0.3.0)

sorry I don't have the example to share at the moment. I'll have to reinstall the latest version of pywinrm to recreate some examples. I'll try to do it later this week.  

Thank you
HS

**Comment by ltamaster** [comment]
no problem, which is your remote windows version?

**Comment by hs-hub-world** [comment]
Windows 2012 R2
PS version: 
![image](https://user-images.githubusercontent.com/20629911/57237008-202f4300-6fdb-11e9-8717-586e975fd6e0.png)

**Comment by ltamaster** [comment]
I wasn't able to reproduce it with python 2.7.10 and a Windows Server 2012.
Checking it with  2.7.5

**Comment by hs-hub-world** [comment]
sorry I had a typo, I update the post it's Win version 2016

**Comment by ltamaster** [comment]
Sorry I wasn't able to reproduce it with the same scenario.
Please let me know if you can share your job (it could be useful).

I have the feeling that the line 70-71 is producing the error 
```
print("Warning: there was a problem converting the Powershell"
                  " error message: %s" % (e))
``` 
But I need to know why that handler is reached 
I will remove that line, let me know if you get a different result.

Thanks
Luis

**Comment by ltamaster** [comment]
Hi @ondrejbaranek,
what kind of command or string are you running?

I would like to reproduce that error.

Thanks
Luis

**Comment by ondrejbaranek** [comment]
It is PowerShell script, runs fine until section with: puppet apply site.pp --modulepath=modules --hiera_config=hiera.yaml

**Comment by ltamaster** [comment]
Hi @ondrejbaranek , 

Could you try the snapshot version?

**Comment by ondrejbaranek** [comment]
Already tried, same error.

**Comment by ltamaster** [comment]
Did you tried py-winrm-plugin-2.0.3-SNAPSHOT.zip? or the previous one? 
Notice that I generated a new SNAPSHOT version when I sent you the previous message 
Luis

**Comment by hs-hub-world** [comment]
I'll try the snapshot version later today or tomorrow, to add little more context, the error occurred when executing PS1 from the remote node and not when doing direct execution from rundeck/adhoc command. Maybe related to encoding?

**Comment by ondrejbaranek** [comment]
2.0.3 snapshot is even worse, it is translating the characters wrongly: it is inline script copied from UTF8 CRLF
in the script it is: Remove-Item -path "c:\ProgramData\PuppetLabs\puppet\cache"
 Remove-Item ?"path "c:\ProgramData\PuppetLabs\puppet\cache"
+ CategoryInfo          : ObjectNotFound: (?path c:String) [Remove-Item], DriveNotFoundException

**Comment by ltamaster** [comment]
@ondrejbaranek  
I wasn't able to reproduce that.
To replicate what you did, are you running a remote script that contains that `Remove-Item -path "xxx"` command, or are you running that from rundeck (like part of an inline script step)
I tested both cases and I didn't get the issue. 

What I got, which is probably the issue, that it is not displayed correctly some special characters like  `write-host "Ñuñoa"`

**Comment by ltamaster** [comment]
@hs-hub-world @ondrejbaranek 
I am generating a new snapshot version. I was able to deal with special characters.
Please let me know if this works for you
https://github.com/rundeck-plugins/py-winrm-plugin/releases/tag/2.0.2-SNAPSHOT

<img width="681" alt="Screenshot 2019-05-10 14 11 57" src="https://user-images.githubusercontent.com/6034968/57549103-a7a8e900-7330-11e9-9acd-e214ec04eada.png">
<img width="751" alt="Screenshot 2019-05-10 14 12 50" src="https://user-images.githubusercontent.com/6034968/57549105-a7a8e900-7330-11e9-8898-a3483c0648a9.png">
<img width="1097" alt="Screenshot 2019-05-10 14 16 12" src="https://user-images.githubusercontent.com/6034968/57549106-a8417f80-7330-11e9-957a-58ae5585fc8e.png">
<img width="566" alt="Screenshot 2019-05-10 14 34 20" src="https://user-images.githubusercontent.com/6034968/57549133-ba232280-7330-11e9-91fe-1d147a15c78a.png">
<img width="1100" alt="Screenshot 2019-05-10 14 34 28" src="https://user-images.githubusercontent.com/6034968/57549135-babbb900-7330-11e9-9272-2314c7d4399a.png">

**Comment by hs-hub-world** [comment]
the snapshot version seems to be working fine for me...

Thank you
HS

**Comment by ltamaster** [comment]
great @hs-hub-world  thanks for the feedback

**Comment by ondrejbaranek** [comment]
@ltamaster the latest snapshot works so far. Thanks!

**Comment by ltamaster** [comment]
I generated a new release.
