### ISSUE TITLE
Question: how to load older version of plugin in Rundeck

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck-plugins/py-winrm-plugin#29]
This is a technical question. how do you load a specific version of py-winrm in rundeck -? Because when I place the py-winrm-plugin-x.x.x. file in the /var/lib/rundeck/libext folder and I restart rundeck svc it seems rundeck keeps downloading (or from some other src-?) it uses the latest version -?  the only workaround I found is to use the same py-winrm-plugin-x.x.x version by overwriting the file, but I was hoping I could use any version and rundeck would honor whatever version is in the folder.

**Comment by ltamaster** [comment]
IHI @hs-hub-world,
It sounds like a rundeck bug, which is your rundeck version?.

Luis
