### ISSUE TITLE
Passing Special character "<" in py-winrm for scripts causes an error. 

### ISSUE THREAD

**Issue by fgutierrezz** [rundeck-plugins/py-winrm-plugin#30]
Rundeck 3.0.20 Cluster 
confirmed with py-winrm-plugin 1.0.1 , 2.0.1  , 2.0.3 

The issue is triggered when using special character "<" as input for remote scripts . 

Example: 

1. Create a project and job with py-winrm configured 

2. Create a step "Command" to run 
c:\windows\system32\cscript.exe /nologo C:\temp\VB\WUA_SearchDownloadInstall.vbs < c:\temp\input.txt

3. This causes an error if executed using the plugin. 

Error: 
Execution finished with the following error:
18:35:20			At line:1 char:118
18:35:20			 At line:1 char:118
18:35:20			+ ... oadInstall.vbs < c:\temp\input.txt
18:35:20			+ ... oadInstall.vbs < c:\temp\input.txt

If the same command is executed from CMD.exe works properly. 

[input.txt](https://github.com/rundeck-plugins/py-winrm-plugin/files/3175219/input.txt)

[WUA_SearchDownloadInstall.vbs.txt](https://github.com/rundeck-plugins/py-winrm-plugin/files/3175223/WUA_SearchDownloadInstall.vbs.txt)

**Comment by ltamaster** [comment]
Can you check the SNAPSHOT release that I have been working on?

**Comment by fgutierrezz** [comment]
Yes, the same issue with 1.0, 2.0.1 and 2.0.2 and 2.0.3

**Comment by ltamaster** [comment]
I couldn't reproduce the issue

1) The character `<` is reserved for PS
<img width="918" alt="Screenshot 2019-12-16 12 42 21" src="https://user-images.githubusercontent.com/6034968/70920692-c1ff1f80-2001-11ea-9e20-09aa813790b2.png">

2) If I run the script using CMD, a prompt is opened, so this script is not compatible on rundeck

<img width="942" alt="Screenshot 2019-12-16 12 36 53" src="https://user-images.githubusercontent.com/6034968/70920745-d5aa8600-2001-11ea-912c-99ea604c02d3.png">
