### ISSUE TITLE
Rundeck calling python and not picking up right env

### ISSUE THREAD

**Issue by kuradikurat** [rundeck-plugins/py-winrm-plugin#42]
Hi,

I'm sorry for the short write-up but possible might affect others with same environment mixture of running rundeck.

Debian 10, rundeck_3.2.0 from repo.
`$ pip install pywirm`
`$ pip show pywinrm`
`
Name: pywinrm
Version: 0.4.1
Summary: Python library for Windows Remote Management
Home-page: http://github.com/diyan/pywinrm/
Author: Alexey Diyan
Author-email: alexey.diyan@gmail.com
License: MIT license
**Location: /usr/local/lib/python2.7/dist-packages**
Requires: six, xmltodict, requests, requests-ntlm
Required-by:
`

CASE1:
Executing winrm-exec.py from console (under rundeck execution user) works.

CASE2:
Executing a rundeck job that triggers winrm-exec.py execution fails with error message
`[ERROR  ]  winrm not installed, try: pip install pywinrm (winrm-exec.py:196)[root]`

CAUSE:
sys.path does not contain a valid dir for winrm lookup
In my case, sys.path was like this while rundeck job executed it:
`['/var/lib/rundeck/libext/cache/py-winrm-plugin-2.0.3', '/lib/python2.7', '/lib/python2.7/plat-x86_64-linux-gnu', '/lib/python2.7/lib-tk', '/lib/python2.7/lib-old', '/lib/python2.7/lib-dynload', '/lib/python2.7/dist-packages']`

I had to alter the winrm-exec.py manually and add the following:
`sys.path.insert(0, "/usr/local/lib/python2.7/dist-packages")`

It does not look like a solid fix for that and problem is somewhere else. Any suggestions?

**Comment by ltamaster** [comment]
hi @kuradikurat 

I think I recently merged a PR (https://github.com/rundeck-plugins/py-winrm-plugin/pull/35) that includes an option to define the path of the python interpreter.

<img width="1086" alt="Screenshot 2020-01-22 09 17 42" src="https://user-images.githubusercontent.com/6034968/72893600-2c3d6b00-3cf8-11ea-9bcb-cda750e97868.png">


You can try that.

Luis
