### ISSUE TITLE
Error Override option?

### ISSUE THREAD

**Issue by meatsac** [rundeck-plugins/py-winrm-plugin#46]
I have a need to override an error code and continue. With PowerShell we can use $ErrorActionPreference, however the block from the winrm-exec.py script always stops the job regardless of this setting. Any way this can be overridden?

if tsk.e_std:
    log.error("Execution finished with the following error")
    log.error(tsk.e_std)
    sys.exit(1)
else:
    sys.exit(tsk.stat)

**Comment by ltamaster** [comment]
Hi @meatsac 
A new flag was added and you can avoid that behavior
https://github.com/rundeck-plugins/py-winrm-plugin#configuration
https://github.com/rundeck-plugins/py-winrm-plugin/tree/master#running-scripts

Luis
