### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\ufeff' in position 22: ordinal not in range(128)

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck-plugins/py-winrm-plugin#60]
This issue for some reason only happens on some of the 5x servers. This particular server is win 2008 R2

[ERROR  ]  Execution finished with the following error (winrm-exec.py:286)[root]
--
01:05:16 | --- Logging error ---
01:05:16 | Traceback (most recent call last):
01:05:16 | File "/usr/lib64/python3.6/logging/__init__.py", line 996, in emit
01:05:16 | stream.write(msg)
01:05:16 | UnicodeEncodeError: 'ascii' codec can't encode character '\ufeff' in position 22: ordinal not in range(128)
01:05:16 | Call stack:
01:05:16 | File "/var/lib/rundeck/libext/cache/py-winrm-plugin-2.0.7/winrm-exec.py", line 287, in <module>
01:05:16 | log.error(tsk.e_std)
01:05:16 | Message: '\ufeffYou cannot call a method on a null-valued expression.\r\nAt C:\\WINDOWS\\TEMP\\39449-68892-PRINT-LA01P-V-dispatch-script.tmp.ps1:16 char:47\r\n+             SessionState = $User.STATE.Replace <<<< ("Disc", "Disconnected")\r\n    + CategoryInfo          : InvalidOperation: (Replace:String) [], RuntimeEx \r\n   ception\r\n    + FullyQualifiedErrorId : InvokeMethodOnNull\r\n \r\n'
01:05:16 | Arguments: ()
01:05:17 | Failed: NonZeroResultCode: [WinRMPython] Result code: 1

![image](https://user-images.githubusercontent.com/20629911/89160507-081fd980-d526-11ea-83c9-f9c1278cd650.png)

similar issue ref: https://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20

RUNDECK
APIVERSION : 35
BASE : /var/lib/rundeck
BUILD : 3.3.1-20200727
BUILDGIT : v3.3.1-0-g7716cc7
SERVERUUID :
VERSION : 3.3.1-20200727

Winrm Version: 
WinRM Node Executor Python | Node Executor | Author: © 2017, Rundeck, Inc. | 2.0.7

**Comment by ltamaster** [comment]
Hi @hs-hub-world 

Can you share your windows remote version?
The command/job that you are running it could be useful too.

Thanks

**Comment by hs-hub-world** [comment]
Hi @ltamaster 
OS: Windows Server 2008 R2 Enterprise

Little more data
when running this command in ad-hoc fashion it fails: **Get-WmiObject Win32_OperatingSystem**

![image](https://user-images.githubusercontent.com/20629911/89592855-86b89780-d802-11ea-93a2-3af2e650c162.png)


When running the same command directly from the server ps command it works fine:
![image](https://user-images.githubusercontent.com/20629911/89598609-13b71d00-d812-11ea-923c-c063c9895169.png)

Thank you,
HS

**Comment by EddyKIL** [comment]
Hi, @hs-hub-world did you get solution for that?

**Comment by hs-hub-world** [comment]
Yes, I am good. Thanks!

**Comment by EddyKIL** [comment]
How did you ? i'm facing a similar error using py-winrm 2.1.1 with python3.6.

**Comment by hs-hub-world** [comment]
It had to do with encoding limitations from Python.  
We end up upgrading to the next extension version at that time - Py-Winrm 2.08, I am sure 2.1.1 should be fine too.
We also upgraded Python which is version Python 3.8.9 at this point.
