### ISSUE TITLE
kerberos auth type is not working

### ISSUE THREAD

**Issue by jplassnibatt** [rundeck-plugins/py-winrm-plugin#61]
v 2.0.8

configuration:
![image](https://user-images.githubusercontent.com/34582874/89334497-98643880-d664-11ea-8f91-a84252aabc80.png)

error:
![image](https://user-images.githubusercontent.com/34582874/89335579-3573a100-d666-11ea-86c1-cb75a1880986.png)

working fine on 2.0.7.-

**Comment by ltamaster** [comment]
fixed 2.0.9
