### ISSUE TITLE
Command step with option value keeps moving semicolon inside a single quote.

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck-plugins/py-winrm-plugin#62]
Hi,
I am not sure if this a Rundeck issue or py-winrm-plugin issue. 

 I have this RD Job with command step: $svcAcct = "${option.SvcActName}"; Get-Process * -IncludeUserName |?{$_.username -like "*$($svcAcct)*"}

Every time we run the RD job it moves the semicolon inside a single quote.
![image](https://user-images.githubusercontent.com/20629911/89470055-b21e8200-d72f-11ea-95da-207d360e6fe9.png)

RUNDECK
APIVERSION : 35
BASE : /var/lib/rundeck
BUILD : 3.3.1-20200727
BUILDGIT : v3.3.1-0-g7716cc7
SERVERUUID :
VERSION : 3.3.1-20200727

Plugin version:
WinRM Node Executor Python | Node Executor | Author: © 2017, Rundeck, Inc. | 2.0.8

Thank you
HS

**Comment by ltamaster** [comment]
Hi @hs-hub-world 
That is how command steps works
please take a look
https://docs.rundeck.com/docs/manual/node-steps/builtin.html#quoting-arguments-to-steps
