### ISSUE TITLE
PyWinRM fails when using options or arguments with simple quotes

### ISSUE THREAD

**Issue by nvalenzuela20** [rundeck-plugins/py-winrm-plugin#70]
**Environment:**
Rundeck Enterprise 3.3.6
PyWinRM 2.0.11 - CMD interpreter (Powershell not allowed)
Not happening on JSCH for linux nodes.

When using options or arguments to send the command to Windows, Rundeck adds simple quotes to the command if a variable is concatenated with any word.

CMD doesn't recognize simple quotes

Options:
![image](https://user-images.githubusercontent.com/35808955/103090592-38990a80-45d0-11eb-8830-7de3358a9f50.png)

![image](https://user-images.githubusercontent.com/35808955/103090963-692d7400-45d1-11eb-8d4e-78ab32b12c44.png)

Arguments:

![image](https://user-images.githubusercontent.com/35808955/103090502-ed7ef780-45cf-11eb-971b-ec7350f20f11.png)

![image](https://user-images.githubusercontent.com/35808955/103090903-40a57a00-45d1-11eb-9932-ef1a95d3a818.png)

**Comment by nvalenzuela20** [comment]
Tested by @dlvcrk

**Comment by jtobard** [comment]
closed by #71
