### ISSUE TITLE
kerberos authentication method

### ISSUE THREAD

**Issue by jplassnibatt** [rundeck-plugins/py-winrm-plugin#9]
Hi
Any chance to add Kerberos to the authentication method?
Now only "basic", "credssp" and "ntlm" are displayed in the node executor section.

**Comment by adalziso** [comment]
I was able to configure kerberos and run a simple test using rundeck pywinrm[keberos]

2 steps are required:

1) update project properties under
/var/rundeck/projects/<PROJECT_NAME>/etc
from
project.plugin.FileCopier.WinRMcpPython.authtype=basic
project.plugin.NodeExecutor.WinRMPython.authtype=basic
to
project.plugin.FileCopier.WinRMcpPython.authtype=kerberos
project.plugin.NodeExecutor.WinRMPython.authtype=kerberos

sed -i 's/Python.authtype=basic/Python.authtype=kerberos/g' project.properties


2) Creae an up front rundeck subjob that executs kinit command:

echo $RD_OPTION_KERBEROS_PASS | kinit $RD_OPTION_KERBEROS_USER


Are there any other possible issues ?
Additinal links:

https://github.com/diyan/pywinrm#valid-transport-options

https://github.com/diyan/pywinrm/blob/master/README.md

"kerberos: Will use Kerberos authentication for domain accounts which only works when the client is in the same domain as the server and the required dependencies are installed. Currently a Kerberos ticket needs to be initialized outside of pywinrm using the kinit command."
